global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'healthcare-backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'ml-api'
    static_configs:
      - targets: ['ml-api:8000']
